on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1

      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: apply db migration
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_OWNER }}
        run: |
          npm install
          cd shared
          npx prisma migrate deploy

      - name: tofu vars
        working-directory: infra
        run: |                    
          REPO_NAME=${GITHUB_REPOSITORY##*/}
          
          touch terraform.tfvars
          echo "app_name = \"$REPO_NAME\"" >> terraform.tfvars
          echo "cloudflare_zone_id = \"${{ secrets.CLOUDFLARE_ZONE_ID }}\"" >> terraform.tfvars
          echo "watcher_instance_type = \"${{ secrets.WATCHER_INSTANCE_TYPE }}\"" >> terraform.tfvars

      - name: tofu init
        working-directory: infra
        run: |
          
          tofu init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="region=${{ vars.AWS_REGION }}"

      - name: build lambda
        run: |
          cd shared
          npx prisma generate
          cd ../api
          npm run build:lambda
          zip -j dist/lambda.zip api/dist/lambda.mjs

      - name: deploy aws
        working-directory: infra
        run: |
          tofu apply -auto-approve \
          -replace="aws_instance.watch_server"

      - name: build frontend
        working-directory: client
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: |
          npx vite build

      - name: deploy frontend
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy client/dist --project-name=dog-up-ya
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
